#!/usr/bin/env python3
"""Generate 'meaningfully wrong' Conway txs by surgically mutating a real
valid fixture, so the inspector's Class-A / network SHACL shapes fire on a
genuinely decoded transaction (not a crafted graph). Single source of truth:
emits one .hex per example + a manifest the UI picker and the test both read."""
import sys, json, copy, cbor2, pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1] / "specs/001-ledger-functional-layer/fixtures"
BASE = (ROOT / "conway-mainnet-tx.hex").read_text().strip()
AMARU_OWNER_KEY = (ROOT / "sundae-swap-usdm-disbursement.hex").read_text().strip()
OUT = ROOT / "broken"
base_tx = cbor2.loads(bytes.fromhex(BASE))

def enc(tx): return cbor2.dumps(tx).hex()

examples = []
def add(slug, label, severity, shape, desc, mutate):
    tx = cbor2.loads(bytes.fromhex(BASE))
    mutate(tx)
    hexs = enc(tx)
    (OUT / f"{slug}.hex").write_text(hexs + "\n")
    examples.append({"slug": slug, "label": label, "severity": severity,
                     "shape": shape, "description": desc, "bytes": len(hexs)//2})

def empty_inputs(tx): tx[0][0] = []
def ref_overlap(tx): tx[0][18] = list(tx[0][0])          # a reference input == a spent input
def network_mismatch(tx): tx[0][15] = 0                  # body says testnet; outputs are mainnet addrs
def aux_hash_unexpected(tx): tx[3] = None                # body has aux-hash (key 7) but no aux data
def aux_hash_missing(tx): del tx[0][7]                   # aux data present but body has no aux-hash

add("empty-inputs", "Empty input set", "violation", "InputSetEmptyUTxO",
    "Transaction spends nothing — the input set is empty.", empty_inputs)
add("reference-input-overlap", "Reference input overlaps a spent input", "violation",
    "ReferenceInputOverlapsWithInput",
    "A UTxO appears as both a spent input and a reference input.", ref_overlap)
add("network-mismatch", "Network id mismatch", "violation", "NetworkConsistency",
    "Body network id is testnet while the output addresses are mainnet.", network_mismatch)
add("aux-hash-unexpected", "Auxiliary-data hash without metadata", "violation",
    "AuxiliaryDataHashPresentButNotExpected",
    "Body carries an auxiliary-data hash but the transaction has no metadata.", aux_hash_unexpected)
add("aux-hash-missing", "Metadata without auxiliary-data hash", "violation",
    "AuxiliaryDataHashMissing",
    "Transaction has metadata but the body omits its auxiliary-data hash.", aux_hash_missing)

(OUT / "manifest.json").write_text(json.dumps(examples, indent=2) + "\n")

# --- emit the PureScript Examples module (single source of truth for the UI picker) ---
# A valid contrast example: the unmutated conway-mainnet fixture.
ps_rows = [{
    "slug": "valid-conway-mainnet", "label": "Valid Conway transaction", "severity": "valid",
    "shape": "", "description": "A real mainnet transaction that conforms to every phase-1 shape.",
    "hex": BASE,
}, {
    "slug": "amaru-owner-key-resolution", "label": "Amaru owner-key resolution", "severity": "valid",
    "shape": "", "description": "A real transaction whose required signer credentials resolve from a selected book.",
    "hex": AMARU_OWNER_KEY,
}]
for e in examples:
    ps_rows.append({**e, "hex": (OUT / f"{e['slug']}.hex").read_text().strip()})

def ps_str(s): return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'
lines = [
    "-- Generated by tools/gen-broken-examples.py. Do not edit by hand.",
    "module Examples (Example, examples) where",
    "",
    "type Example =",
    "  { slug :: String",
    "  , label :: String",
    "  , severity :: String -- \"valid\" | \"warning\" | \"violation\"",
    "  , shape :: String",
    "  , description :: String",
    "  , cbor :: String",
    "  }",
    "",
    "examples :: Array Example",
    "examples =",
]
for i, r in enumerate(ps_rows):
    open_b = "[ " if i == 0 else ", "
    lines.append(f"  {open_b}{{ slug: {ps_str(r['slug'])}")
    lines.append(f"    , label: {ps_str(r['label'])}")
    lines.append(f"    , severity: {ps_str(r['severity'])}")
    lines.append(f"    , shape: {ps_str(r['shape'])}")
    lines.append(f"    , description: {ps_str(r['description'])}")
    lines.append(f"    , cbor: {ps_str(r['hex'])}")
    lines.append("    }")
lines.append("  ]")
PS_OUT = pathlib.Path(__file__).resolve().parents[1] / "docs/inspector/src/Examples.purs"
PS_OUT.write_text("\n".join(lines) + "\n")

for e in examples:
    print(f"{e['slug']:26} {e['severity']:9} {e['shape']:38} {e['bytes']}B")
print("wrote", len(examples), "fixtures +manifest to", OUT)
print("wrote", len(ps_rows), "examples to", PS_OUT)
